version: '3.1'
services:
  app:
    container_name: guestbook
    image: juanantpineda/guestbook:v1
    restart: always
    environment:
      DB_HOST: mimariadb
      DB_USER: guestbook
      DB_PASSWORD: guestbook
      DB_NAME: guestbook
    ports:
      - 8089:80
    volumes:
      - guestbook_log:/var/log/apache2/
    depends_on:
      - db
  db:
    container_name: mimariadb
    image: juanantpineda/mimariadb:v1
    restart: always
    environment:
      MARIADB_DATABASE: guestbook
      MARIADB_USER: guestbook
      MARIADB_PASSWORD: guestbook
      MARIADB_ROOT_PASSWORD: root
    volumes:
      - mariadbpineda_data:/var/lib/mysql
volumes:
    mariadbpineda_data:
    guestbook_log: